version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped  # 開発時のみ起動し、手動で止めない限り継続
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data:
